use std::mem::ManuallyDrop;

// ── CRC32 IEEE 802.3 ─────────────────────────────────────────────────────

const fn crc32_byte(mut crc: u32, byte: u8) -> u32 {
    crc ^= byte as u32;
    let mut i = 0;
    while i < 8 {
        crc = if crc & 1 == 1 {
            (crc >> 1) ^ 0xEDB8_8320
        } else {
            crc >> 1
        };
        i += 1;
    }
    crc
}

const fn crc32(data: &[u8]) -> u32 {
    let mut crc: u32 = 0xFFFF_FFFF;
    let mut i = 0;
    while i < data.len() {
        crc = crc32_byte(crc, data[i]);
        i += 1;
    }
    !crc
}

// ── Email constants (generated by scripts/gen-email.ts) ──────────────────
// Format : hash:<crc32_hex> username:<scrambled> domain:<label0>.<label1>...
// Rebuild: bun scripts/gen-email.ts <email>  →  paste output into lib.rs
//          then run: wasm-pack build wasm --target web --out-dir pkg
const HASH: u32 = 0xF49C2AFC;
const USERNAME: &[u8] = b"tno";
const LABELS: &[&[u8]] = &[b"zl251", b"evd"];

// ── Permutation brute-force ──────────────────────────────────────────────

fn permutations(s: &[u8]) -> Vec<Vec<u8>> {
    if s.len() <= 1 {
        return vec![s.to_vec()];
    }
    let mut out = Vec::new();
    for i in 0..s.len() {
        let head = s[i];
        let mut rest = s.to_vec();
        rest.remove(i);
        for mut tail in permutations(&rest) {
            tail.insert(0, head);
            out.push(tail);
        }
    }
    out
}

fn try_domain(
    user: &[u8],
    label_perms: &[Vec<Vec<u8>>],
    idx: usize,
    prefix: &mut Vec<u8>,
) -> Option<String> {
    if idx == label_perms.len() {
        let mut candidate = user.to_vec();
        candidate.push(b'@');
        candidate.extend_from_slice(prefix);
        if crc32(&candidate) == HASH {
            return String::from_utf8(candidate).ok();
        }
        return None;
    }
    for perm in &label_perms[idx] {
        let prev_len = prefix.len();
        if idx > 0 {
            prefix.push(b'.');
        }
        prefix.extend_from_slice(perm);
        if let Some(email) = try_domain(user, label_perms, idx + 1, prefix) {
            return Some(email);
        }
        prefix.truncate(prev_len);
    }
    None
}

fn solve() -> String {
    let label_perms: Vec<Vec<Vec<u8>>> = LABELS.iter().map(|l| permutations(l)).collect();
    for u in permutations(USERNAME) {
        if let Some(email) = try_domain(&u, &label_perms, 0, &mut Vec::new()) {
            return email;
        }
    }
    String::new()
}

// ── ABI ──────────────────────────────────────────────────────────────────
//
// Returns the result string as a packed u64: (len << 32) | ptr.
// The string is leaked into wasm linear memory; the JS side reads the bytes
// directly out of `memory.buffer`. Safe because reveal() is called at most
// once per page session, after which the WebAssembly.Module is GC'd.

#[unsafe(no_mangle)]
pub extern "C" fn reveal() -> u64 {
    let s = ManuallyDrop::new(solve());
    let ptr = s.as_ptr() as u32;
    let len = s.len() as u32;
    ((len as u64) << 32) | (ptr as u64)
}
