[package]
name = "l5z12-wasm"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]

[profile.release]
opt-level = "z"
lto = true
strip = true
panic = "abort"

[package.metadata.wasm-pack.profile.release]
# -Oz: aggressive size optimisation; strip non-runtime sections.
wasm-opt = [
    "-Oz",
    "--enable-bulk-memory",
    "--strip-debug",
    "--strip-producers",
]
