/**
 * Generate CRC32 hash + scrambled username/domain constants for the WASM email module.
 * The plaintext email is passed as a CLI argument and never written to any file.
 *
 * Usage:  bun scripts/gen-email.ts <email>
 * Output: paste the printed snippet into wasm/src/lib.rs
 */

const email = process.argv[2];

if (!email || !email.includes("@") || !email.includes(".")) {
  console.error("Usage: bun scripts/gen-email.ts <email@domain.tld>");
  process.exit(1);
}

// ── CRC32 IEEE 802.3 ──────────────────────────────────────────────────────

function crc32(s: string): number {
  const bytes = new TextEncoder().encode(s);
  let crc = 0xffffffff;
  for (const b of bytes) {
    crc ^= b;
    for (let i = 0; i < 8; i++)
      crc = crc & 1 ? (crc >>> 1) ^ 0xedb88320 : crc >>> 1;
  }
  return (crc ^ 0xffffffff) >>> 0;
}

// ── Fisher-Yates shuffle ──────────────────────────────────────────────────

function shuffle(chars: string[]): string[] {
  const a = [...chars];
  for (let i = a.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [a[i], a[j]] = [a[j]!, a[i]!];
  }
  return a;
}

// ── Generate ──────────────────────────────────────────────────────────────

const atIdx = email.indexOf("@");
const username = email.slice(0, atIdx);
const domain = email.slice(atIdx + 1);
const labels = domain.split(".");

const hash = crc32(email);
const scrambledUser = shuffle([...username]).join("");
const scrambledLabels = labels.map((l) => shuffle([...l]).join(""));

const hashHex = `0x${hash.toString(16).toUpperCase().padStart(8, "0")}`;
const labelsRust = scrambledLabels.map((l) => `b"${l}"`).join(", ");

console.log(`
// ── Email constants (generated by scripts/gen-email.ts) ──────────────────
// Format : hash:<crc32_hex> username:<scrambled> domain:<label0>.<label1>...
// Rebuild: bun scripts/gen-email.ts <email>  →  paste output into lib.rs
//          then run: wasm-pack build wasm --target web --out-dir pkg
const HASH: u32     = ${hashHex};
const USERNAME: &[u8] = b"${scrambledUser}";
const LABELS: &[&[u8]] = &[${labelsRust}];
`);
